service: serverlessbackend
plugins:
  - serverless-dotenv-plugin
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - "s3:*"
            - "rekognition:CompareFaces"
            - "rekognition:DetectText"
            - "lambda:InvokeFunction"

functions:
  getPresignedUrl:
    handler: handler/s3/getPresignedUrl.handler
    events:
      - http:
          path: /getPreSignedUrl
          method: POST
          cors:
            origin: "*"
  detectTextFromImage:
    handler: handler/rekognition/detectText.handler
    events:
      - http:
          path: /detectTextFromImage
          method: POST
          cors:
            origin: "*"
  compareFaces:
    handler: handler/rekognition/compareFaces.handler
    events:
      - http:
          path: /compareFaces
          method: POST
          cors:
            origin: "*"
  getResult:
    handler: handler/main.handler
    events:
      - http:
          path: /getResult
          method: POST
          cors:
            origin: "*"
  createProfile:
    handler: handler/profile/createProfile.handler
    timeout: 15
    events:
      - http:
          path: /createProfile
          method: POST
          cors:
            origin: "*"
  getProfile:
    handler: handler/profile/getProfile.handler
    timeout: 15
    events:
      - http:
          path: /getProfile
          method: GET
          cors:
            origin: "*"
resources:
  Resources:
    BilguunTechBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: bilguun-tech-bucket
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - "*"
              AllowedMethods:
                - PUT
                - GET
                - POST
              AllowedOrigins:
                - "*"
